// alert('暴雨梨花针');
// prompt('请输入的小舞的颜色');
// var age=10;
// console.log(age);
// var mingiz='宇思彤';
// var dizhi='圣魂村';
// var nianling='30';
// var gongzi='15000';
// console.log(mingiz);
// console.log(dizhi);
// console.log(nianling);
// console.log(gongzi);
// var mingiz1 = prompt('请输入姓名');
// alert('欢迎'+mingiz1);
// var apple1='青苹果';
// var apple2='红苹果';
// var apple3;
// console.log('apple1：'+apple1);
// console.log('apple2：'+apple2);
// apple3=apple1;
// apple1=apple2;
// apple2=apple3;
// console.log('apple1：'+apple1);
// console.log('apple2：'+apple2);
// console.log(isNaN(nianling));
// console.log(Number.MAX_VALUE);
// console.log(Number.MIN_VALUE);
// console.log(Number.MAX_VALUE*2);
// console.log(-Number.MAX_VALUE*2);
// alert('酷热难耐，火辣的太阳底下，我挺拔的身姿，成为了最独特的风景\n"春风秋水辞"\n我与秋风皆过客，君携秋水揽星河')
// var name1='my name is liyu';
// alert(name1.length);
// console.log('宇'+'思'+'彤');
// var mynahew='love';
// var njka=666;
// console.log('宇'+ mynahew +'彤' + njka);
// var age=prompt('你的年龄是多少？');
// alert('你的年龄是' + age + '!');
// var num=10068;
// console.log(typeof num);
// var str='彤彤逼黑';
// console.log(typeof str);
// var aal=true;
// console.log(typeof aal);
// var num = 150;
// var str = num.toString();
// var hhh = String(num);
// var jjj = num + '';
// console.log('num是：' + typeof num);
// console.log(typeof str);
// console.log(typeof hhh);
// console.log(typeof str);
// console.log(typeof jjj);
// var ppp = prompt();
// var www = parseInt(ppp);
// var eee = parseFloat(ppp);
// var rrr = Number(ppp);
// var ttt = ppp - 0;
// console.log('jjj是：' + typeof jjj);
// console.log(typeof www);
// console.log(www);
// console.log(typeof eee);
// console.log(eee);
// console.log(typeof rrr);
// console.log(rrr);
// console.log(typeof ttt);
// console.log(ttt);
// var years = prompt('请输入你的出生年份！')
// var age = 2022 - years;
// alert('你的年龄是：' + age);
// 计算器案例
// var one = parseFloat(prompt('请输入第一个加数'));
// var two = parseFloat(prompt('请输入第二个加数'));
// var he = one + two;
// alert('两个数之和是：' + he);
// console.log(typeof Boolean('null'));
// console.log(typeof Boolean('100'));
// console.log(Boolean(null));
// console.log(Boolean('100'));
// var mz = prompt('姓名');
// var xb = prompt('性别');
// var nl = prompt('年龄');
// alert('你的名字是：' + mz + '\n你的性别是：' + xb + '\n你的年龄是:' + nl)
// console.log(1 + 1);
// console.log(10 - 1);
// console.log(5 * 5);
// console.log(4 / 2);
// console.log(12 % 5);
// console.log(0.07 * 100);
// var x = 5;
// for (x; x <= 10; x++) {
//     console.log(x);
// }
var a = 10;
var x = 10;
// console.log(x++ + a);
console.log(++x + a);